### ISSUE TITLE
Reordering of chapters in the Spec

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-tck#12]
The new version of the [specification](https://docs.google.com/document/d/12KhosAFriGCczBs6gwtJJDfg_QlANT92_lhxUWO2gCY) got a few chapters reordered or elements like `Prefix` introduced to existing ones. This affects the numbering of test cases which must be addressed in the TCK.

**Comment by thodorisbais** [comment]
I had a look at this one yesterday, but couldn't really figure out what was missing.

**Comment by keilw** [comment]
That's why I just closed it, I must have done this on the fly when adding `mix()` which I removed again. Thanks for checking
