### ISSUE TITLE
Further reduce JavaDoc warnings/errors 

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-tck#20]
Reduce the errors and warnings for JavaDoc generation.

**Comment by thodorisbais** [comment]
What needs to be done here? I can only see a NPE while building:  ![Screenshot 2019-04-21 at 01 45 32](https://user-images.githubusercontent.com/5684688/56463568-56fc3b00-63d7-11e9-8b39-218d0b15c5e2.png)

**Comment by keilw** [comment]
Never seen that, what Java version did you try?

**Comment by keilw** [comment]
@thodorisbais Did this ever occur again?

**Comment by thodorisbais** [comment]
(Unfortunately) yes, maybe it's indeed a good point to investigate during our Adopt-a-JSR day. I'll create a new issue, though, since (it seems like) it's more of a prerequisite to work on this one.

**Comment by keilw** [comment]
This one's tiny btw, but a good opportunity to get them down to zero.
