### ISSUE TITLE
Add tests for overloaded Unit methods

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-tck#28]
Add signature tests for new methods added by https://github.com/unitsofmeasurement/unit-api/issues/191

**Comment by thodorisbais** [comment]
So, the only changes that need to be applied are in `UnitConversionTest`, right?

**Comment by keilw** [comment]
No mostly `UnitInterfaceTest`

**Comment by thodorisbais** [comment]
Indeed (; it was already late midnight when I was typing this comment 😂 ). This is now ready with #29 .

**Comment by thodorisbais** [comment]
Closed with #29
