### ISSUE TITLE
[Maven Build] Error while generating Javadocs

### ISSUE THREAD

**Issue by thodorisbais** [unitsofmeasurement/unit-tck#30]
The following issue occurs while building:

![Screenshot 2019-05-13 at 23 28 24](https://user-images.githubusercontent.com/5684688/57655784-fc6d8d80-75d6-11e9-9a68-684e567582ef.png)

System
- macOS Mojave 10.14.4
- Java 11

This is a prerequisite for #20 .

**Comment by keilw** [comment]
Did you try a different JDK?

**Comment by thodorisbais** [comment]
So, basically yes, (I think) I've tried with any possible JDK, but without any success:
![Screenshot 2019-06-01 at 16 28 01](https://user-images.githubusercontent.com/5684688/58749771-636dbc00-848a-11e9-818e-fccb4007303f.png)

It looks like we have an issue with Mac.

**Comment by keilw** [comment]
I would say the JDK has a problem on MacOS, there is nothing the TCK could directly do about that. How old is MacOS 10.14.4?
