### ISSUE TITLE
Minor refinements in test documentation

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-tck#31]
There could be some minor refinements in test documentation, e.g.
"Test method: 4.2.1.2.1 Ensure the divide() operation is implemented."
might say
"Test method: 4.2.1.2.1 Ensure the divide(**Unit**) operation is implemented."
instead, to align with other method tests.

**Comment by thodorisbais** [comment]
Heheh that's really funny, I was doubting about it while updating it for the last time.

**Comment by thodorisbais** [comment]
Closed with  8b20758
